# Generated by Django 5.1.7 on 2025-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('Available', 'Disponible'), ('Occupied', 'Ocupada'), ('Reserved', 'Reservada')], max_length=20),
        ),
    ]
