# Generated by Django 5.1.7 on 2025-06-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_table_is_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_reserved',
        ),
    ]
