# Generated by Django 5.1.7 on 2025-05-31 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tax_rate',
        ),
    ]
