# Generated by Django 5.1.7 on 2025-05-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_image_url_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemoption',
            name='allows_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='max_selections',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='menuitemoption',
            name='price_adjustment',
            field=models.IntegerField(default=2000),
        ),
    ]
