# Generated by Django 5.1.7 on 2025-05-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_price'),
        ('menu', '0003_alter_menuitemoption_allows_multiple_and_more'),
    ]

    operations = [
    ]
