# Generated by Django 5.1.7 on 2025-06-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_merge_20250531_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('plato_fuerte', 'Plato Fuerte'), ('postres', 'Postres'), ('bebidas', 'Bebidas'), ('combo', 'Combo'), ('Salchipapas', 'Salchipapas'), ('Hamburguesas', 'Hamburguesas'), ('Emparedados', 'Emparedados'), ('Perros', 'Perros'), ('Bebidas', 'Bebidas')], max_length=50),
        ),
    ]
