# Generated by Django 5.1.7 on 2025-06-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuitem_category_alter_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Entradas', 'Entradas'), ('Plato Fuerte', 'Plato Fuerte'), ('Postres', 'Postres'), ('Bebidas', 'Bebidas'), ('Combo', 'Combo'), ('Salchipapas', 'Salchipapas'), ('Hamburguesas', 'Hamburguesas'), ('Emparedados', 'Emparedados'), ('Perros', 'Perros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='Sin descripción', max_length=200),
        ),
    ]
