# Generated by Django 5.1.7 on 2025-06-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_tax_remove_order_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Preparando', 'Preparando'), ('Lista', 'Lista')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
