# Generated by Django 5.1.7 on 2025-06-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Preparando', 'Preparando'), ('Lista', 'Lista')], default='En espera', max_length=20),
        ),
    ]
